# Generated by Django 2.2 on 2021-10-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('paymenttype', models.CharField(max_length=255)),
                ('upvotes', models.IntegerField()),
            ],
        ),
    ]
